version: '3.9'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  django:
    container_name: django
    build: 
      context: .
    
    command: sh -c "python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8001:8000
    depends_on:
      - db

  celery:
    container_name: celery
    build: 
      context: .
    volumes:
      - .:/code
    